HOST = '0.0.0.0'
PORT = 5801

# DRIVER VISION
DRIVER_CAMERA_PORT = 0
DRIVER_CAMERA_WIDTH = 424
DRIVER_CAMERA_HEIGHT = 240  # 320
DRIVER_CAMERA_FPS = 20
DRIVER_CAMERA_BRIGHTNESS = -10
DRIVER_CAMERA_EXPOSURE = 20
DRIVER_STREAM_INTERVAL = 0.03
DRIVER_STREAM_RETRY_INTERVAL = 0.5

# TARGETING
TARGETING_INTERVAL = 0.05
TARGETING_RETRY_INTERVAL = 0.5
TARGETING_CAMERA_PORT = 1
TARGETING_CAMERA_WIDTH = 424
TARGETING_CAMERA_HEIGHT = 240  # 320
TARGETING_CAMERA_FPS = 15
TARGETING_CAMERA_WHITE_BALANCE = 3000
TARGETING_CAMERA_BRIGHTNESS = -10
TARGETING_CAMERA_EXPOSURE = 20
TARGETING_LOWER_HSV_BOUND = (79, 140, 76)  # Green for spartaaaa
TARGETING_UPPER_HSV_BOUND = (99, 255, 255)

# NETWORK TABLES
ROBOT_IP_ADDRESS = '10.50.45.85'
# ROBOT_IP_ADDRESS = '127.0.0.1'
NT_DRIVER_DIRECTION_SELECTOR = 'editable--chooser--driver_direction'
NT_AUTONOMOUS_COMMAND_SELECTOR = 'editable--chooser--autonomous_command'
